const SHOP_TOKEN = "shop_token";
const USER_TOKEN = "token";

const ORDER_STATUS_PROCESSING = "Processing";
const ORDER_STATUS_TRANSFER_TO_DELIVERY_PARTNET =
  "Transferred to delivery partner";
const ORDER_STATUS_SHIPPING = "Shipping";
const ORDER_STATUS_RECIVED = "Received";
const ORDER_STATUS_ON_THE_WAY = "On the way";
const ORDER_STATUS_DELIVERED = "Delivered";
const ORDER_STATUS_PROCESSING_REFUND = "Processing refund";

module.exports = {
  SHOP_TOKEN,
  USER_TOKEN,
  ORDER_STATUS_DELIVERED,
  ORDER_STATUS_ON_THE_WAY,
  ORDER_STATUS_PROCESSING,
  ORDER_STATUS_RECIVED,
  ORDER_STATUS_SHIPPING,
  ORDER_STATUS_TRANSFER_TO_DELIVERY_PARTNET,
  ORDER_STATUS_PROCESSING_REFUND,
};
